version: "3.8"

services:
  th3pl4gu3:
    container_name: Th3pl4gu3
    image: docker.pkg.github.com/mervin16/th3pl4gu3/th3pl4gu3:0.1
    networks:
      - th3pl4gu3_net
    ports:
      - 8082:8082
    restart: always

networks:
  th3pl4gu3_net:
    name: th3pl4gu3_network
    driver: bridge
