version: "3.8"

services:
  th3pl4gu3:
    container_name: th3pl4gu3
    build: ./
    image: mervin16/th3pl4gu3
    networks:
      - th3pl4gu3_net
    ports:
      - 8082:8082
    env_file:
      - config_local.env
    restart: always

networks:
  th3pl4gu3_net:
    name: th3pl4gu3_network
    driver: bridge
