version: "3.8"

services:
  th3pl4gu3:
    container_name: th3pl4gu3
    build: ./
    image: mervin16/th3pl4gu3:dev
    networks:
      - th3pl4gu3_net
    expose:
      - 8082
    env_file:
      - config_local.env
    restart: always

  nginx_th3pl4gu3:
    image: nginx
    container_name: nginx_th3pl4gu3
    ports:
      - "8082:80"
    networks:
      - th3pl4gu3_net
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - th3pl4gu3
    restart: always

networks:
  th3pl4gu3_net:
    name: th3pl4gu3_network
    driver: bridge
